// بيانات تجريبية (Sample/Fixture Data) تُستخدم فقط في الاختبارات الآلية (Vitest)
// لا تُستخدم إطلاقاً كبيانات افتراضية داخل التطبيق الفعلي عند تسليمه للعميل.
// راجع demo-data.ts للحصول على القيم الفارغة الحقيقية المستخدمة في التطبيق.

import type {
  Bank,
  Cashbox,
  Company,
  CreditDebitNote,
  Customer,
  Employee,
  EmployeeDeduction,
  FinancialYear,
  Invoice,
  PaymentVoucher,
  Payroll,
  PurchaseInvoice,
  ReceiptVoucher,
  Supplier,
  Vehicle,
  AppSettings,
} from "@/types";

export const SAMPLE_COMPANY: Company = {
  id: "comp_sa_001",
  name: "شركة أسطول النقل السريع للخدمات اللوجستية",
  phone: "0542520544",
  email: "info@fleet-logistics.com",
  address: "الرياض — طريق الملك فهد — حي الصحافة",
  currency: "ر.س",
  vat_rate: 15,
  vat_note: "الأسعار خاضعة لضريبة القيمة المضافة 15%",
  commercial_reg: "1010789456",
  tax_number: "310123456700003",
  plan_type: "trial",
  client_code: "CL-892147",
  trial_start: new Date().toISOString(),
  trial_end: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  subscription_start: null,
  subscription_end: null,
  is_active: true,
  created_at: new Date().toISOString(),
};

export const SAMPLE_YEARS: FinancialYear[] = [
  {
    id: 1,
    year: 2026,
    date_from: "2026-01-01",
    date_to: "2026-12-31",
    status: "open",
    notes: "السنة المالية الحالية لعام 2026",
  },
];

export const SAMPLE_CUSTOMERS: Customer[] = [
  {
    id: 1,
    code: "CUST-0001",
    name: "شركة المراعي المحدودة",
    address: "الرياض — المدينة الصناعية الثانية",
    phone: "0112456789",
    tax_number: "300021458900003",
    commercial_reg: "1010123456",
    city: "الرياض",
    opening_balance: 15000,
    notes: "حساب رئيسي — سداد خلال 30 يوماً",
  },
  {
    id: 2,
    code: "CUST-0002",
    name: "مجموعة العليان التجارية",
    address: "الدمام — طريق الميناء",
    phone: "0138945612",
    tax_number: "300098745600003",
    commercial_reg: "2050456789",
    city: "الدمام",
    opening_balance: 0,
    notes: "نقل حاويات من ميناء الملك عبد العزيز",
  },
  {
    id: 3,
    code: "CUST-0003",
    name: "شركة أسمنت اليمامة",
    address: "الخرج — طريق حرض",
    phone: "0114987123",
    tax_number: "300065412300003",
    commercial_reg: "1010567890",
    city: "الخرج",
    opening_balance: 8500,
    notes: "نقل مواد سائبة وكلنكر",
  },
];

export const SAMPLE_EMPLOYEES: Employee[] = [
  {
    id: 1,
    code: "EMP-001",
    name: "أحمد منصور الحارثي",
    nationality: "سعودي",
    phone: "0501234567",
    emp_type: "driver",
    base_salary: 4500,
    notes: "سائق تريلا خط دولي ومحلي",
  },
  {
    id: 2,
    code: "EMP-002",
    name: "محمود عبد الرحمن السيد",
    nationality: "مصري",
    phone: "0559876543",
    emp_type: "driver",
    base_salary: 3800,
    notes: "سائق شاحنة نقل مبرد",
  },
  {
    id: 3,
    code: "EMP-003",
    name: "سلطان عبد العزيز الدوسري",
    nationality: "سعودي",
    phone: "0564567890",
    emp_type: "admin",
    base_salary: 6000,
    notes: "مدير العمليات والتشغيل",
  },
];

export const SAMPLE_VEHICLES: Vehicle[] = [
  {
    id: 1,
    code: "VEH-01",
    plate_number: "أ ب ج 1234",
    vehicle_type: "شاحنة مرسيدس أكتروس 2022",
    default_driver_id: 1,
    notes: "شاحنة رأس تريلا مع سطحة",
    driver_name: "أحمد منصور الحارثي",
  },
  {
    id: 2,
    code: "VEH-02",
    plate_number: "د هـ و 5678",
    vehicle_type: "شاحنة فولفو FH16 مبرد",
    default_driver_id: 2,
    notes: "شاحنة ثلاجة نقل بضائع مبردة",
    driver_name: "محمود عبد الرحمن السيد",
  },
  {
    id: 3,
    code: "VEH-03",
    plate_number: "س ص ع 9012",
    vehicle_type: "شاحنة مان جوانب عالية",
    default_driver_id: null,
    notes: "نقل الحبوب والمواد الصلبة",
  },
];

export const SAMPLE_CASHBOXES: Cashbox[] = [
  {
    id: 1,
    code: "CASH-01",
    name: "الخزينة الرئيسية (الإدارة)",
    created_date: "2026-01-01",
    opening_balance: 50000,
    notes: "خزينة النقدية الرئيسية في مقر الشركة",
  },
  {
    id: 2,
    code: "CASH-02",
    name: "عهدة الحركة والنقليات",
    created_date: "2026-01-01",
    opening_balance: 10000,
    notes: "عهدة كارتات ووقود الحركة السريعة",
  },
];

export const SAMPLE_BANKS: Bank[] = [
  {
    id: 1,
    code: "BNK-01",
    name: "مصرف الراجحي — الحساب التجاري",
    created_date: "2026-01-01",
    account_number: "458000123456789",
    iban: "SA4480000458000123456789",
    opening_balance: 180000,
    notes: "الحساب البنكي الأساسي للتحصيلات والفواتير",
  },
  {
    id: 2,
    code: "BNK-02",
    name: "البنك الأهلي السعودي (SNB)",
    created_date: "2026-01-01",
    account_number: "123000987654321",
    iban: "SA1210000123000987654321",
    opening_balance: 75000,
    notes: "حساب مسيرات الرواتب والمدفوعات الحكومية",
  },
];

export const SAMPLE_SUPPLIERS: Supplier[] = [
  {
    id: 1,
    code: "SUPP-001",
    name: "شركة الدريس للخدمات البترولية",
    name_en: "Aldrees Petroleum",
    phone: "0112345678",
    email: "sales@aldrees.com",
    contact_person: "خالد التميمي",
    address: "الرياض — طريق الدائري الشرقي",
    opening_balance: 12000,
    tax_number: "300147852300003",
    commercial_reg: "1010369852",
    notes: "حساب آجل للديزل والوقود ومحطات الطرق",
  },
  {
    id: 2,
    code: "SUPP-002",
    name: "شركة الجفالي لقطع غيار الشاحنات",
    name_en: "Juffali Truck Parts",
    phone: "0126789123",
    email: "parts@juffali.com",
    contact_person: "عمر الحربي",
    address: "جدة — كيلو 14 طريق مكة",
    opening_balance: 5000,
    tax_number: "300258741200003",
    commercial_reg: "4030147852",
    notes: "صيانة وإطارات وفلاتر لشاحنات مرسيدس",
  },
];

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: 1,
    number: 1001,
    date: "2026-02-10",
    customer_id: 1,
    vat_rate: 15,
    notes: "نقل شحنات ألبان ومنتجات غذائية من المصنع إلى مستودعات القصيم",
    attachments: [],
    container_number: "MSCU-8492015",
    trips: [
      {
        id: 1,
        invoice_id: 1,
        vehicle_id: 1,
        driver_id: 1,
        from_loc: "الرياض (المصنع الرئيسي)",
        to_loc: "بريدة (المستودع المركزي)",
        qty: 2,
        unit_price: 2400,
        price: 4800,
        container_numbers: ["MSCU-8492015", "MSCU-8492016"],
        notes: "نقل مبرد درجة حرارة 4 مئوية",
        vehicle_name: "أ ب ج 1234",
        driver_name: "أحمد منصور الحارثي",
        expenses: [
          {
            id: 1,
            trip_id: 1,
            expense_type: "fuel",
            qty: 1,
            unit_amount: 450,
            amount: 450,
            source: "cash",
            account_kind: "cashbox",
            account_id: 2,
            notes: "ديزل طريق القصيم السريع",
          },
          {
            id: 2,
            trip_id: 1,
            expense_type: "card",
            qty: 2,
            unit_amount: 50,
            amount: 100,
            source: "cash",
            account_kind: "cashbox",
            account_id: 2,
            notes: "كارتة ميزان وميناء جاف",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    number: 1002,
    date: "2026-02-18",
    customer_id: 2,
    vat_rate: 15,
    notes: "نقل حاويات 40 قدم من ميناء الملك عبد العزيز بالدمام إلى الرياض",
    attachments: [],
    container_number: "TGHU-9920147",
    trips: [
      {
        id: 2,
        invoice_id: 2,
        vehicle_id: 2,
        driver_id: 2,
        from_loc: "ميناء الملك عبد العزيز (الدمام)",
        to_loc: "الرياض (المستودع الرئيسي)",
        qty: 1,
        unit_price: 3200,
        price: 3200,
        container_numbers: ["TGHU-9920147"],
        notes: "شحن سريع خلال 24 ساعة",
        vehicle_name: "د هـ و 5678",
        driver_name: "محمود عبد الرحمن السيد",
        expenses: [
          {
            id: 3,
            trip_id: 2,
            expense_type: "fuel",
            qty: 1,
            unit_amount: 500,
            amount: 500,
            source: "cash",
            account_kind: "cashbox",
            account_id: 2,
            notes: "ديزل طريق الدمام",
          },
        ],
      },
    ],
  },
];

export const SAMPLE_RECEIPTS: ReceiptVoucher[] = [
  {
    id: 1,
    number: 501,
    date: "2026-02-12",
    account_kind: "bank",
    account_id: 1,
    voucher_type: "customer",
    customer_id: 1,
    amount: 10000,
    description: "دفعة من حساب شركة المراعي تحويل سريع عبر مصرف الراجحي",
  },
];

export const SAMPLE_PAYMENTS: PaymentVoucher[] = [
  {
    id: 1,
    number: 701,
    date: "2026-02-05",
    account_kind: "cashbox",
    account_id: 1,
    voucher_type: "advance",
    employee_id: 1,
    trip_id: null,
    vehicle_id: null,
    vehicle_expense: "",
    quantity: 1,
    unit_amount: 1000,
    amount: 1000,
    description: "سلفة نقدية على راتب شهر فبراير للسائق أحمد الحارثي",
  },
  {
    id: 2,
    number: 702,
    date: "2026-02-08",
    account_kind: "cashbox",
    account_id: 1,
    voucher_type: "vehicle",
    employee_id: null,
    trip_id: null,
    vehicle_id: 1,
    vehicle_expense: "صيانة وتغيير زيوت وفلاتر",
    quantity: 1,
    unit_amount: 650,
    amount: 650,
    description: "تغيير زيت شاحنة أكتروس 1234",
  },
];

export const SAMPLE_DEDUCTIONS: EmployeeDeduction[] = [
  {
    id: 1,
    number: 101,
    date: "2026-02-02",
    employee_id: 2,
    amount: 200,
    reason: "مخالفة تجاوز سرعة على طريق الخرج",
    notes: "سددت الشركة المخالفة وتُخصم من الراتب",
  },
];

export const SAMPLE_PURCHASES: PurchaseInvoice[] = [
  {
    id: 1,
    number: 201,
    date: "2026-02-01",
    purchase_type: "credit",
    supplier_id: 1,
    supplier_ref: "ALD-99412",
    expense_category: "fuel",
    vehicle_id: null,
    account_kind: null,
    account_id: null,
    vat_rate: 15,
    vat_included: false,
    notes: "فاتورة ديزل وبنزين محطات الطرق لشهر يناير",
    items: [
      {
        id: 1,
        purchase_invoice_id: 1,
        item_name: "ديزل للشاحنات (بطاقات تموين)",
        unit: "لتر",
        qty: 3000,
        unit_price: 1.15,
        vat_rate: 15,
        notes: "تموين مباشر من محطات الدريس",
      },
    ],
  },
];

export const SAMPLE_APP_SETTINGS: AppSettings = {
  app_name: "نظام المحاسبة وإدارة النقليات واللوجستيات",
  app_version: "2.4.0 Desktop Pro",
  developer_name: "محمد عبده",
  developer_title: "خبير ومطور النظم المحاسبية والإدارية",
  developer_country: "المملكة العربية السعودية / جمهورية مصر العربية",
  phone: "00966542520544",
  whatsapp: "00966542520544",
  telegram: "conta_shepo",
  email: "conta.shepo@gmail.com",
  support_hours: "يومياً على مدار الساعة 24/7",
  about_text:
    "برنامج سطح مكتب متكامل ومتطور ومبني خصيصاً لشركات ومؤسسات النقل البري، النقليات، التريلات، المقطورات، الحاويات، الشحن اللوجستي، وخدمات النولون. يتميز النظام بالدقة المتناهية، دعم العمل أوفلاين دون انقطاع، التوافق التام مع ويندوز 7 و 8 و 10 و 11، والربط السحابي مع كلاود فلير وبوت تليجرام للتحكم وإصدار التراخيص ومتابعة المشتركين وخدمة العملاء.",
  payment_note:
    "لتفعيل الاشتراك السنوي أو الشهري أو شراء ترخيص دائم، يمكنك التواصل مباشرة عبر واتساب أو تليجرام واستلام مفتاح الترخيص فوراً.",
  copyright: "جميع الحقوق محفوظة للمطور © محمد عبده",
  monthly_price: 100,
  yearly_price: 1000,
  pricing_discount_note: "وفر 200 ريال سنوياً مع الباقة السنوية!",
  visibility: {
    developer_country: true,
    support_hours: true,
    pricing: true,
  },
  custom_fields: [
    {
      id: "f_support_whatsapp",
      label: "دعم فني مباشر واتساب",
      value: "00966542520544",
      type: "whatsapp",
      enabled: true,
    },
    {
      id: "f_official_tg",
      label: "قناة التحديثات في تليجرام",
      value: "https://t.me/conta_shepo",
      type: "telegram",
      enabled: true,
    },
    {
      id: "f_tech_spec",
      label: "التوافقية",
      value: "متوافق مع ويندوز 7 و 8 و 8.1 و 10 و 11 (32 بت و 64 بت)",
      type: "text",
      enabled: true,
    },
  ],
  cloudflare_worker_url: "https://logistics-desktop-api.workers.dev",
};
